name: Rahil Arora - Personal Blog
description: Security and stuff!
meta_description: "Rahil Arora's Personal Blog about Security and stuff!"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: 
domain_name: 'http://www.rahilarora.com'

# Details for the RSS feed generator
url:            'www.rahilarora.com'
author:         'Rahil Arora'
