# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rahil Arora
tagline:          'Personal Website'
description:      '<span class="aaaa">Security Enthusiast | </span><span class="aaaa">n00b Blogger | </span><span class="aaaa">Tennis Lover</span>'
url:              http://rahilarora.com
baseurl:          /
privacy_url:      /privacy
google_analytics:   true
gems:               
    - jekyll-sitemap
disqus:             true
disqus_username:    'lihararora'

author:
  name:           'Rahil Arora'
  url:            https://twitter.com/lihararora

paginate:         5

# Custom vars
version:          2.1.0

github:
    url:            https://github.com/lihararora

twitter:
    url:            https://twitter.com/lihararora

linkedin:
    url:            https://www.linkedin.com/in/lihararora

stackoverflow:
    url:            http://stackexchange.com/users/1471315/rahil-arora?tab=accounts
