# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Rahil Arora
tagline:             'Personal Blog'
description:         'Securiy related stuff'
url:                 www.rahilarora.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Rahil Arora
  url:               http://www.rahilarora.com
  email:             contact@rahilarora.com

# Custom vars
version:             1.0.0
