# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Serve

host: 0.0.0.0

# Permalinks
permalink:        pretty

# Setup
title:            Rahil Arora
tagline:          'Personal Website'
description:      '<span class="aaaa">Security Enthusiast | </span><span class="aaaa">n00b Blogger | </span><span class="aaaa">Tennis Lover</span>'
url:              http://rahilarora.com
baseurl:          /
privacy_url:      /privacy
google_analytics:   true
gems:
  - jekyll-sitemap
gems: [jekyll-paginate]
disqus:             true
disqus_username:    'lihararora'

author:
  name:           'Rahil Arora'
  url:            https://twitter.com/lihararora

paginate:         5
future: true

# Custom vars
version:          3.2.1

github:
    url:            https://github.com/lihararora

twitter:
    url:            https://twitter.com/lihararora

linkedin:
    url:            https://www.linkedin.com/in/lihararora

stackoverflow:
    url:            http://stackexchange.com/users/1471315/rahil-arora?tab=accounts
